[package]
name = "zed-datadog-mcp"
version = "0.2.0"
edition = "2024"
publish = false
license = "MIT"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.6.0"
serde = "1.0"
schemars = "0.8"
